language: python
version: 
  - "3.6"

before_install:
  - python -m pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

install:
  - python -m pip install .

script:
  - script: python manage.py test