language: python
version: 
  - "3.6"

before_install:
  - python -m pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate


install:
  - pip install requirements.txt

script:
  - script: python manage.py test